# Generated by Django 2.1.2 on 2018-10-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter file name', max_length=150)),
                ('mainFile', models.FileField(help_text='Upload a file', null=True, upload_to='uploads/item/photos/')),
            ],
        ),
    ]
