# Generated by Django 2.1.2 on 2018-10-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0003_auto_20181015_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='noOfPages',
            field=models.IntegerField(default=0),
        ),
    ]
